"""Added datapoints table

Revision ID: ee4e12e4316a
Revises: 
Create Date: 2019-08-30 11:10:18.583358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4e12e4316a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datapoints')
    # ### end Alembic commands ###
